In [1]:
# Some useful settings for interactive work
%load_ext autoreload
%autoreload 2

%matplotlib widget

import torch
torch.set_float32_matmul_precision('high')

In [2]:
# Import the relevant modules
import numpy as np
from PIL import Image
import torch.nn.functional as F
import matplotlib.pyplot as plt
import sousvide.synthesize.rollout_generator as rg
import sousvide.synthesize.observation_generator as og
import sousvide.control.networks.feature_extractors as fe
import sousvide.utilities.feature_utilities as fu
import figs.visualize.generate_videos as gv
import figs.utilities.transform_helper as th

In [3]:
cohort = "features"

data_method = "eval_single"
eval_method = "eval_single"

scene = "mid_gate"

courses = ["traverse"]   

roster = ["clanGhostBear"]

In [4]:
# Generate Rollouts
rg.generate_rollout_data(cohort,courses,scene,data_method)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


Loading latest checkpoint from load_dir

✅ Done loading checkpoint from outputs/mid_gate/splatfacto/2024-10-07_145741/nerfstudio_models/step-000029999.ckpt

Output()

In [8]:
og.generate_observation_data(cohort,roster)

Generating observation data with subsample ratio 1.0 for...
 Cohort : features
 Roster : ['clanGhostBear']
 Courses: ['traverse']

Output()

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-6.48020824e-08  2.56225600e-07 -3.11439126e-07 -7.91603694e-05]
 [-1.39925348e-05  5.53491241e-05 -1.17352085e-05 -5.30071809e-04]
 [-8.61208381e-05  3.40834113e-04 -6.05032640e-05 -1.30592528e-03]
 [-2.64439209e-04  1.04724626e-03 -1.77597754e-04 -2.78816069e-03]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.39277328e-05  5.50928985e-05 -1.14237694e-05 -4.50911440e-04]
 [-8.60560361e-05  3.40577887e-04 -6.01918249e-05 -1.22676491e-03]
 [-2.64374407e-04  1.04699003e-03 -1.77286314e-04 -2.70900032e-03]
 [-5.95931206e-04  2.36206938e-03 -3.93064629e-04 -5.17478153e-03]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.21283033e-05  2.85484989e-04 -4.87680555e-05 -7.75853468e-04]
 [-2.50446674e-04  9.91897131e-04 -1.65862545e-04 -2.25808888e-03]
 [-5.82003473e-04  2.30697648e-03 -3.81640859e-04 -4.72387010e-03]
 [-1.11248948e-03  4.41439176e-03 -7.25593640e-04 -8.36444150e-03]]

[[ 0.          0.          0.          0.        ]
 [-0.00017832  0.00070641 -0.00011709 -0.00148224]
 [-0.00050988  0.00202149 -0.00033287 -0.00394802]
 [-0.00104036  0.00412891 -0.00067683 -0.00758859]
 [-0.00181373  0.00720709 -0.00117736 -0.0125254 ]]

[[ 0.          0.          0.          0.        ]
 [-0.00033156  0.00131508 -0.00021578 -0.00246578]
 [-0.00086204  0.00342249 -0.00055973 -0.00610635]
 [-0.00163541  0.00650067 -0.00106026 -0.01104317]
 [-0.00269353  0.01072173 -0.00174449 -0.01734189]]

[[ 0.          0.          0.          0.        ]
 [-0.00053049  0.00210742 -0.00034395 -0.00364057]
 [-0.00130385  0.00518559 -0.00084448 -0.00857739]
 [-0.00236198  0.00940665 -0.00152871 -0.01487611]
 [-0.00374434  0.01493544 -0.00242228 -0.0225586 ]]

[[ 0.          0.          0.          0.        ]
 [-0.00077337  0.00307818 -0.00050053 -0.00493681]
 [-0.00183149  0.00729924 -0.00118476 -0.01123554]
 [-0.00321385  0.01282802 -0.00207833 -0.01891803]
 [-0.00495725  0.01982121 -0.00320525 -0.02797281]]

[[ 0.          0.          0.          0.        ]
 [-0.00105812  0.00422106 -0.00068423 -0.00629872]
 [-0.00244048  0.00974984 -0.0015778  -0.01398122]
 [-0.00418388  0.01674303 -0.00270472 -0.023036  ]
 [-0.00632221  0.02534837 -0.00408723 -0.03342692]]

[[ 0.          0.          0.          0.        ]
 [-0.00138236  0.00552878 -0.00089357 -0.00768249]
 [-0.00312576  0.01252197 -0.00202049 -0.01673727]
 [-0.00526409  0.02112731 -0.003403   -0.0271282 ]
 [-0.00782809  0.03148292 -0.00506144 -0.03880182]]

[[ 0.          0.          0.          0.        ]
 [-0.0017434   0.00699319 -0.00112692 -0.00905478]
 [-0.00388173  0.01559853 -0.00250943 -0.01944571]
 [-0.00644573  0.02595413 -0.00416787 -0.03111932]
 [-0.00946281  0.03818786 -0.00612058 -0.04401092]]

[[ 0.          0.          0.          0.        ]
 [-0.00213833  0.00860534 -0.00138251 -0.01039093]
 [-0.00470233  0.01896094 -0.00304095 -0.02206454]
 [-0.00771941  0.03119467 -0.00499366 -0.03495614]
 [-0.01121348  0.04542358 -0.00725687 -0.04899468]]

[[ 0.          0.          0.          0.        ]
 [-0.002564    0.0103556  -0.00165844 -0.01167362]
 [-0.00558108  0.02258933 -0.00361115 -0.02456521]
 [-0.00907515  0.03681824 -0.00587436 -0.03860375]
 [-0.01306647  0.05314818 -0.00846215 -0.05371582]]

[[ 0.          0.          0.          0.        ]
 [-0.00301708  0.01223372 -0.00195271 -0.01289159]
 [-0.00651115  0.02646264 -0.00421592 -0.02693014]
 [-0.01050247  0.04279257 -0.00680371 -0.0420422 ]
 [-0.01500753  0.06131773 -0.0097279  -0.05815505]]

[[ 0.          0.          0.          0.        ]
 [-0.00349407  0.01422891 -0.00226321 -0.01403854]
 [-0.00748539  0.03055885 -0.004851   -0.02915061]
 [-0.01199045  0.04908401 -0.0077752  -0.04526346]
 [-0.01702188  0.06988664 -0.01104535 -0.0623073 ]]

[[ 0.          0.          0.          0.        ]
 [-0.00399132  0.01632994 -0.00258779 -0.01511207]
 [-0.00849638  0.03485509 -0.00551198 -0.03122492]
 [-0.01352781  0.05565773 -0.00878214 -0.04826875]
 [-0.01909431  0.07880792 -0.0124055  -0.06617839]]

[[ 0.          0.          0.          0.        ]
 [-0.00450506  0.01852516 -0.00292419 -0.01611285]
 [-0.00953649  0.03932779 -0.00619435 -0.03315669]
 [-0.01510299  0.06247798 -0.00981771 -0.05106632]
 [-0.02120925  0.08803341 -0.01379918 -0.06978219]]

[[ 0.          0.          0.          0.        ]
 [-0.00503143  0.02080264 -0.00327016 -0.01704384]
 [-0.01059793  0.04395282 -0.00689351 -0.03495347]
 [-0.01670419  0.06950826 -0.01087499 -0.05366934]
 [-0.02335087  0.09751413 -0.01521716 -0.07313814]]

[[ 0.          0.          0.          0.        ]
 [-0.0055665   0.02315019 -0.00362336 -0.01790963]
 [-0.01167276  0.04870562 -0.00760483 -0.0366255 ]
 [-0.01831944  0.07671149 -0.011947   -0.0560943 ]
 [-0.02550316  0.10720046 -0.0166501  -0.07626913]]

[[ 0.          0.          0.          0.        ]
 [-0.00610626  0.02555543 -0.00398148 -0.01871587]
 [-0.01275294  0.05356131 -0.00832364 -0.03818467]
 [-0.01993667  0.08405027 -0.01302674 -0.0583595 ]
 [-0.02764999  0.1170424  -0.01808871 -0.07919975]]

[[ 0.          0.          0.          0.        ]
 [-0.00664668  0.02800588 -0.00434217 -0.0194688 ]
 [-0.01383041  0.05849484 -0.00904527 -0.03964363]
 [-0.02154373  0.09148697 -0.01410724 -0.06048388]
 [-0.02977517  0.12698981 -0.01952373 -0.08195484]]

[[ 0.          0.          0.          0.        ]
 [-0.00718372  0.03048896 -0.0047031  -0.02017483]
 [-0.01489704  0.06348109 -0.00976507 -0.04101508]
 [-0.02312849  0.09898393 -0.01518156 -0.06248604]
 [-0.03186256  0.13699262 -0.02094598 -0.08455831]]

[[ 0.          0.          0.          0.        ]
 [-0.00771332  0.03299213 -0.00506197 -0.02084025]
 [-0.01594476  0.06849497 -0.01047846 -0.04231121]
 [-0.02467884  0.10650366 -0.01624287 -0.06438348]
 [-0.03389611  0.14700104 -0.02234643 -0.08703224]]

[[ 0.          0.          0.          0.        ]
 [-0.00823144  0.03550284 -0.00541649 -0.02147096]
 [-0.01696552  0.07351153 -0.0111809  -0.04354323]
 [-0.02618279  0.11400892 -0.01728446 -0.06619199]
 [-0.03585989  0.15696576 -0.02371623 -0.08939618]]

[[ 0.          0.          0.          0.        ]
 [-0.00873408  0.03800869 -0.00576441 -0.02207227]
 [-0.01795134  0.07850607 -0.01186797 -0.04472103]
 [-0.02762845  0.12146292 -0.01829974 -0.06792522]
 [-0.03773823  0.16683812 -0.02504675 -0.09166668]]

[[ 0.          0.          0.          0.        ]
 [-0.00921727  0.04049739 -0.00610355 -0.02264876]
 [-0.01889438  0.08345423 -0.01253532 -0.04585295]
 [-0.02900415  0.12882943 -0.01928234 -0.06959441]
 [-0.03951569  0.17657032 -0.02632962 -0.09385697]]

[[ 0.          0.          0.          0.        ]
 [-0.00967711  0.04295684 -0.00643177 -0.02320419]
 [-0.01978689  0.08833204 -0.01317878 -0.04694565]
 [-0.03029843  0.13607293 -0.02022606 -0.07120821]
 [-0.04117717  0.18611557 -0.02755675 -0.09597685]]

[[ 0.          0.          0.          0.        ]
 [-0.01010978  0.0453752  -0.00674701 -0.02374146]
 [-0.02062132  0.09311609 -0.01379429 -0.04800402]
 [-0.03150006  0.14315873 -0.02112498 -0.07277266]
 [-0.04270794  0.19542828 -0.02872041 -0.09803263]]

[[ 0.          0.          0.          0.        ]
 [-0.01051154  0.04774089 -0.00704728 -0.02426256]
 [-0.02139028  0.09778353 -0.01437797 -0.0490312 ]
 [-0.03259816  0.15005308 -0.0219734  -0.07429118]
 [-0.0440937   0.20446416 -0.02981319 -0.10002732]]

[[ 0.          0.          0.          0.        ]
 [-0.01087875  0.05004264 -0.00733069 -0.02476863]
 [-0.02208663  0.10231219 -0.01492612 -0.05002861]
 [-0.03358216  0.15672328 -0.02276591 -0.07576475]
 [-0.0453206   0.21318045 -0.03082811 -0.10196074]]

[[ 0.          0.          0.          0.        ]
 [-0.01120788  0.05226955 -0.00759543 -0.02525998]
 [-0.02270341  0.10668064 -0.01543522 -0.05099612]
 [-0.03444185  0.16313781 -0.02349742 -0.0771921 ]
 [-0.04637534  0.22153595 -0.03175859 -0.10382988]]

[[ 0.          0.          0.          0.        ]
 [-0.01149553  0.05441109 -0.00783979 -0.02573614]
 [-0.02323397  0.11086826 -0.015902   -0.05193212]
 [-0.03516746  0.16926641 -0.02416316 -0.0785699 ]
 [-0.04724515  0.22949127 -0.0325985  -0.10562925]]

[[ 0.          0.          0.          0.        ]
 [-0.01173844  0.05645717 -0.0080622  -0.02619598]
 [-0.02367192  0.11485532 -0.01632337 -0.05283376]
 [-0.03574961  0.17508018 -0.0247587  -0.07989311]
 [-0.04791787  0.23700886 -0.03334218 -0.10735121]]

[[ 0.          0.          0.          0.        ]
 [-0.01193348  0.05839815 -0.00826117 -0.02663778]
 [-0.02401117  0.11862301 -0.0166965  -0.05369713]
 [-0.03617943  0.18055169 -0.02527998 -0.08115523]
 [-0.048382    0.24405317 -0.03398448 -0.10898649]]

[[ 0.          0.          0.          0.        ]
 [-0.01207769  0.06022487 -0.00843534 -0.02705934]
 [-0.02424595  0.12215354 -0.01701881 -0.05451745]
 [-0.03644851  0.18565503 -0.02572331 -0.08234871]
 [-0.04862668  0.25059076 -0.03452074 -0.11052456]]

[[ 0.          0.          0.          0.        ]
 [-0.01216826  0.06192868 -0.00858348 -0.02745811]
 [-0.02437083  0.12543016 -0.01728798 -0.05528936]
 [-0.03654899  0.19036589 -0.02608541 -0.08346522]
 [-0.04864179  0.25659037 -0.03494686 -0.11195414]]

[[ 0.          0.          0.          0.        ]
 [-0.01220257  0.06350148 -0.0087045  -0.02783126]
 [-0.02438073  0.12843721 -0.01750193 -0.05600711]
 [-0.03647353  0.1946617  -0.02636338 -0.08449604]
 [-0.04841795  0.26202307 -0.03525927 -0.11326362]]

[[ 0.          0.          0.          0.        ]
 [-0.01217816  0.06493573 -0.00879743 -0.02817585]
 [-0.02427096  0.13116021 -0.01765888 -0.05666478]
 [-0.03621538  0.19852159 -0.02655478 -0.08543236]
 [-0.04794654  0.2668623  -0.03545498 -0.11444144]]

[[ 0.          0.          0.          0.        ]
 [-0.0120928   0.06622448 -0.00886145 -0.02848893]
 [-0.02403722  0.13358586 -0.01775735 -0.05725651]
 [-0.03576838  0.20192657 -0.02665755 -0.08626559]
 [-0.04721978  0.27108396 -0.03553157 -0.11547649]]

[[ 0.          0.          0.          0.        ]
 [-0.01194442  0.06736138 -0.00889589 -0.02876758]
 [-0.02367558  0.13570208 -0.0177961  -0.05777666]
 [-0.03512698  0.20485948 -0.02667011 -0.08698756]
 [-0.04623069  0.2746665  -0.0354872  -0.11635844]]

[[ 0.          0.          0.          0.        ]
 [-0.01173116  0.06834071 -0.00890021 -0.02900908]
 [-0.02318256  0.1374981  -0.01777422 -0.05821998]
 [-0.03428627  0.20730512 -0.02659131 -0.08759085]
 [-0.04497316  0.27759098 -0.03532064 -0.11707804]]

[[ 0.          0.          0.          0.        ]
 [-0.0114514   0.06915739 -0.00887402 -0.0292109 ]
 [-0.02255511  0.13896441 -0.0176911  -0.05858177]
 [-0.03324199  0.20925027 -0.02642043 -0.08806896]
 [-0.04344196  0.27984113 -0.03503125 -0.11762744]]

[[ 0.          0.          0.          0.        ]
 [-0.01110371  0.06980702 -0.00881708 -0.02937087]
 [-0.02179059  0.14009288 -0.01754641 -0.05885806]
 [-0.03199056  0.21068374 -0.02615723 -0.08841654]
 [-0.04163277  0.2814034  -0.03461901 -0.11800039]]

[[ 0.          0.          0.          0.        ]
 [-0.01068689  0.07028586 -0.00872933 -0.02948719]
 [-0.02088685  0.14087672 -0.01734015 -0.05904567]
 [-0.03052906  0.21159638 -0.02580193 -0.08862952]
 [-0.03954217  0.28226701 -0.0340845  -0.11819243]]

[[ 0.          0.          0.          0.        ]
 [-0.01019996  0.07059086 -0.00861082 -0.02955848]
 [-0.01984217  0.14131052 -0.0170726  -0.05914234]
 [-0.02885529  0.21198115 -0.02535517 -0.08870525]
 [-0.03716772  0.28242398 -0.03342891 -0.11820098]]

[[ 0.          0.          0.          0.        ]
 [-0.00964221  0.07071966 -0.00846178 -0.02958386]
 [-0.01865532  0.14139029 -0.01674435 -0.05914677]
 [-0.02696775  0.21183312 -0.02481809 -0.0886425 ]
 [-0.03450788  0.28186916 -0.03265403 -0.11802539]]

[[ 0.          0.          0.          0.        ]
 [-0.00901312  0.07067063 -0.00828258 -0.02956291]
 [-0.01732554  0.14111346 -0.01635631 -0.05905864]
 [-0.02486567  0.21114949 -0.02419225 -0.08844154]
 [-0.0315621   0.28060027 -0.03176226 -0.11766696]]

[[ 0.          0.          0.          0.        ]
 [-0.00831243  0.07044283 -0.00807374 -0.02949573]
 [-0.01585255  0.14047886 -0.01590968 -0.05887863]
 [-0.02254899  0.20992964 -0.02347968 -0.08810405]
 [-0.02833082  0.27861789 -0.03075658 -0.11712881]]

[[ 0.          0.          0.          0.        ]
 [-0.00754012  0.07003604 -0.00783594 -0.0293829 ]
 [-0.01423656  0.13948681 -0.01540594 -0.05860832]
 [-0.02001839  0.20817506 -0.02268284 -0.08763308]
 [-0.02481543  0.27592549 -0.02964057 -0.11641579]]

[[ 0.          0.          0.          0.        ]
 [-0.00669644  0.06945077 -0.00757    -0.02922542]
 [-0.01247827  0.13813903 -0.0148469  -0.05825019]
 [-0.01727531  0.20588945 -0.02180463 -0.08703289]
 [-0.02101833  0.27252941 -0.02841837 -0.11553423]]

[[ 0.          0.          0.          0.        ]
 [-0.00578183  0.06868825 -0.0072769  -0.02902476]
 [-0.01057887  0.13643868 -0.01423462 -0.05780747]
 [-0.0143219   0.20307864 -0.02084837 -0.08630881]
 [-0.01694289  0.26843884 -0.02709471 -0.1144918 ]]

[[ 0.          0.          0.          0.        ]
 [-0.00479704  0.06775043 -0.00695773 -0.0287827 ]
 [-0.00854006  0.13439038 -0.01357147 -0.05728405]
 [-0.01116106  0.19975059 -0.01981781 -0.08546703]
 [-0.01259349  0.26366583 -0.02567483 -0.1132971 ]]

[[ 0.          0.          0.          0.        ]
 [-0.00374302  0.06663995 -0.00661375 -0.02850134]
 [-0.00636402  0.13200016 -0.01286009 -0.05668433]
 [-0.00779645  0.1959154  -0.01871711 -0.0845144 ]
 [-0.00797545  0.25822522 -0.02416453 -0.11195947]]

[[ 0.          0.          0.          0.        ]
 [-0.002621    0.0653602  -0.00624634 -0.02818299]
 [-0.00405342  0.12927544 -0.01210336 -0.05601306]
 [-0.00423243  0.19158526 -0.01755078 -0.08345813]
 [-0.00309512  0.25213464 -0.0225701  -0.11048854]]

[[ 0.          0.          0.          0.        ]
 [-0.00143242  0.06391524 -0.00585702 -0.02783007]
 [-0.00161143  0.12622506 -0.01130444 -0.05527514]
 [-0.00047412  0.18677444 -0.01632377 -0.08230555]
 [ 0.00204022  0.24541443 -0.02089834 -0.10889397]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.79008074e-04  6.23098210e-02 -5.44742584e-03 -2.74450699e-02]
 [ 9.58301114e-04  1.22859197e-01 -1.04667461e-02 -5.44754845e-02]
 [ 3.47264846e-03  1.81499189e-01 -1.50413237e-02 -8.10639012e-02]
 [ 7.42234730e-03  2.38087577e-01 -1.91565539e-02 -1.07185123e-01]]

[[ 0.          0.          0.          0.        ]
 [ 0.00113731  0.06054938 -0.00501932 -0.02703041]
 [ 0.00365166  0.11918937 -0.0095939  -0.05361883]
 [ 0.00760136  0.17577776 -0.01370913 -0.07974005]
 [ 0.01304208  0.23017966 -0.01735244 -0.10537043]]

[[ 0.          0.          0.          0.        ]
 [ 0.00251435  0.05863999 -0.00457458 -0.02658842]
 [ 0.00646405  0.11522838 -0.00868981 -0.05270964]
 [ 0.01190477  0.16963029 -0.01233312 -0.07834001]
 [ 0.01888934  0.22171877 -0.01549408 -0.10345709]]

[[ 0.          0.          0.          0.        ]
 [ 0.0039497   0.05658839 -0.00411523 -0.02612122]
 [ 0.00939042  0.1109903  -0.00775854 -0.0517516 ]
 [ 0.01637499  0.16307878 -0.0109195  -0.07686867]
 [ 0.02495316  0.21273538 -0.01358995 -0.10145099]]

[[ 0.          0.          0.          0.        ]
 [ 0.00544073  0.05440191 -0.00364331 -0.02563038]
 [ 0.0124253   0.10649039 -0.00680427 -0.05074745]
 [ 0.02100346  0.15614699 -0.00947472 -0.07532977]
 [ 0.03122172  0.20326227 -0.01164881 -0.09935624]]

[[ 0.          0.          0.          0.        ]
 [ 0.00698457  0.05208848 -0.00316096 -0.02511707]
 [ 0.01556274  0.10174508 -0.00583141 -0.04969939]
 [ 0.025781    0.14886036 -0.0080055  -0.07372586]
 [ 0.03768238  0.19333439 -0.00967981 -0.0971752 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.00857817  0.0496566  -0.00267045 -0.02458232]
 [ 0.01879643  0.09677188 -0.00484454 -0.04860879]
 [ 0.03069781  0.14124591 -0.00651885 -0.07205813]
 [ 0.04432171  0.18298873 -0.00769239 -0.09490833]]

[[ 0.          0.          0.          0.        ]
 [ 0.01021826  0.04711528 -0.00217409 -0.02402647]
 [ 0.02211964  0.09158931 -0.0038484  -0.04747581]
 [ 0.03574354  0.13333213 -0.00502194 -0.07032601]
 [ 0.05112555  0.17226414 -0.0056962  -0.09255385]]

[[ 0.          0.          0.          0.        ]
 [ 0.01190138  0.04447403 -0.00167431 -0.02344934]
 [ 0.02552528  0.08621685 -0.00284785 -0.04629954]
 [ 0.04090729  0.12514886 -0.0035221  -0.06852737]
 [ 0.05807905  0.16120124 -0.0037011  -0.09010779]]

[[ 0.          0.          0.          0.        ]
 [ 0.0136239   0.04174282 -0.00117354 -0.0228502 ]
 [ 0.02900591  0.08067483 -0.00184779 -0.04507804]
 [ 0.04617767  0.11672721 -0.00202679 -0.06665845]
 [ 0.06516671  0.14984215 -0.00171711 -0.08756466]]

[[ 0.          0.          0.          0.        ]
 [ 0.01538201  0.03893202 -0.00067426 -0.02222783]
 [ 0.03255377  0.07498439 -0.00085326 -0.04380824]
 [ 0.05154281  0.10809933 -0.00054357 -0.06471445]
 [ 0.07237247  0.13823039  0.00024568 -0.08491736]]

[[ 0.          0.          0.          0.        ]
 [ 0.01717176  0.03605237 -0.000179   -0.02158041]
 [ 0.0361608   0.06916732  0.00013068 -0.04248662]
 [ 0.05699046  0.09929837  0.00091994 -0.06268952]
 [ 0.07967975  0.1264106   0.00217713 -0.08215785]]

[[ 0.          0.          0.          0.        ]
 [ 0.01898904  0.03311494  0.00030968 -0.02090621]
 [ 0.0398187   0.063246    0.00109894 -0.04110911]
 [ 0.06250799  0.09035823  0.00235613 -0.06057743]
 [ 0.08707153  0.11442838  0.0040671  -0.079278  ]]

[[ 0.          0.          0.          0.        ]
 [ 0.02082966  0.03013105  0.00078926 -0.0202029 ]
 [ 0.04351895  0.05724328  0.00204644 -0.03967122]
 [ 0.06808249  0.08131343  0.00375742 -0.05837179]
 [ 0.09453044  0.10232999  0.00590558 -0.07627014]]

[[ 0.          0.          0.          0.        ]
 [ 0.02268929  0.02711223  0.00125719 -0.01946832]
 [ 0.04725283  0.05118238  0.00296816 -0.03816889]
 [ 0.07370078  0.07219893  0.00511633 -0.05606724]
 [ 0.10203878  0.09016214  0.00768268 -0.07312863]]

[[ 0.          0.          0.          0.        ]
 [ 0.02456354  0.02407015  0.00171098 -0.01870057]
 [ 0.05101149  0.0450867   0.00385914 -0.03659892]
 [ 0.07934949  0.06304991  0.00642549 -0.05366031]
 [ 0.10957869  0.07797169  0.00938871 -0.06985117]]

[[ 0.          0.          0.          0.        ]
 [ 0.02644795  0.02101655  0.00214816 -0.01789835]
 [ 0.05478595  0.03897976  0.00471451 -0.03495974]
 [ 0.08501515  0.05390155  0.00767773 -0.0511506 ]
 [ 0.11713218  0.06580539  0.01101426 -0.06644058]]

[[ 0.          0.          0.          0.        ]
 [ 0.02833801  0.0179632   0.00256635 -0.01706139]
 [ 0.05856721  0.03288499  0.00552957 -0.03325225]
 [ 0.09068424  0.04478883  0.0088661  -0.04854223]
 [ 0.12468126  0.05370951  0.0125503  -0.0629069 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.0302292   0.01492179  0.00296322 -0.01619086]
 [ 0.06234623  0.02682563  0.00629975 -0.03148084]
 [ 0.09634325  0.0357463   0.00998395 -0.04584551]
 [ 0.13220804  0.04172957  0.01398821 -0.05926975]]

[[ 0.          0.          0.          0.        ]
 [ 0.03211703  0.01190384  0.00333653 -0.01528998]
 [ 0.06611405  0.02082452  0.00702074 -0.02965465]
 [ 0.10197884  0.02680778  0.01102499 -0.04307889]
 [ 0.13969486  0.02990996  0.01531988 -0.05556113]]

[[ 0.          0.          0.          0.        ]
 [ 0.03399702  0.00892067  0.0036842  -0.01436467]
 [ 0.06986181  0.01490394  0.00768846 -0.02778891]
 [ 0.10757783  0.01800612  0.01198334 -0.04027115]
 [ 0.14712441  0.01829359  0.01653781 -0.05182698]]

[[ 0.          0.          0.          0.        ]
 [ 0.03586479  0.00598327  0.00400425 -0.01342424]
 [ 0.07358081  0.00908545  0.00829914 -0.02590648]
 [ 0.11312739  0.00937291  0.01285361 -0.03746232]
 [ 0.15447984  0.00692149  0.01763519 -0.04812319]]

[[ 0.          0.          0.          0.        ]
 [ 0.03771602  0.00310218  0.00429488 -0.01248224]
 [ 0.0772626   0.00338965  0.00884935 -0.02403808]
 [ 0.11861506  0.00093822  0.01363094 -0.03469895]
 [ 0.16174488 -0.00416741  0.01860593 -0.04450675]]

[[ 0.          0.          0.          0.        ]
 [ 0.03954658  0.00028747  0.00455447 -0.01155583]
 [ 0.08089903 -0.00216396  0.00933605 -0.0222167 ]
 [ 0.12402886 -0.00726959  0.01431105 -0.03202451]
 [ 0.16890387 -0.01493649  0.01944472 -0.04102691]]

[[ 0.          0.          0.          0.        ]
 [ 0.04135245 -0.00245143  0.00478158 -0.01066087]
 [ 0.08448228 -0.00755706  0.00975658 -0.02046868]
 [ 0.12935729 -0.01522395  0.01489025 -0.02947107]
 [ 0.17594179 -0.02535145  0.020147   -0.03771785]]

[[ 0.          0.          0.          0.        ]
 [ 0.04312982 -0.00510563  0.004975   -0.00980781]
 [ 0.08800483 -0.01277253  0.01010866 -0.0188102 ]
 [ 0.13458934 -0.02290003  0.01536541 -0.02705698]
 [ 0.18284426 -0.03538036  0.02070901 -0.03459736]]

[[ 0.          0.          0.          0.        ]
 [ 0.04487501 -0.00766689  0.00513367 -0.0090024 ]
 [ 0.09145951 -0.01779439  0.01039042 -0.01724917]
 [ 0.13971444 -0.03027473  0.01573401 -0.02478955]
 [ 0.18959749 -0.04499353  0.02112778 -0.0316703 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.0465845  -0.0101275   0.00525675 -0.00824678]
 [ 0.09483943 -0.02260783  0.01060035 -0.01578716]
 [ 0.14472248 -0.03732664  0.01599411 -0.0226679 ]
 [ 0.19618827 -0.05416355  0.02140108 -0.02893204]]

[[ 0.          0.          0.          0.        ]
 [ 0.04825493 -0.01248033  0.0053436  -0.00754038]
 [ 0.09813798 -0.02719914  0.01073736 -0.01442112]
 [ 0.14960377 -0.04403605  0.01614433 -0.02068526]
 [ 0.20260397 -0.06286523  0.02152751 -0.02637143]]

[[ 0.          0.          0.          0.        ]
 [ 0.04988305 -0.01471881  0.00539376 -0.00688074]
 [ 0.10134884 -0.03155572  0.01080073 -0.01314488]
 [ 0.15434904 -0.0503849   0.01618391 -0.01883104]
 [ 0.20883252 -0.07107562  0.02150642 -0.02397317]]

[[ 0.          0.          0.          0.        ]
 [ 0.05146579 -0.01683691  0.00540697 -0.00626414]
 [ 0.10446599 -0.03566609  0.01079015 -0.0119503 ]
 [ 0.15894946 -0.05635682  0.01611266 -0.01709243]
 [ 0.21486241 -0.07877403  0.02133796 -0.02171983]]

[[ 0.          0.          0.          0.        ]
 [ 0.0530002  -0.01882918  0.00538318 -0.00568616]
 [ 0.10748367 -0.03951991  0.01070569 -0.01082828]
 [ 0.16339662 -0.06193712  0.01593098 -0.01545569]
 [ 0.22068271 -0.08594199  0.02102307 -0.01959344]]

[[ 0.          0.          0.          0.        ]
 [ 0.05448347 -0.02069073  0.00532251 -0.00514212]
 [ 0.11039642 -0.04310794  0.01054781 -0.00976953]
 [ 0.16768251 -0.06711281  0.01563989 -0.01390728]
 [ 0.22628306 -0.09256335  0.0205635  -0.01757669]]

[[ 0.          0.          0.          0.        ]
 [ 0.05591294 -0.02241721  0.0052253  -0.00462741]
 [ 0.11319904 -0.04642209  0.01031739 -0.00876516]
 [ 0.17179959 -0.07187263  0.01524099 -0.01243457]
 [ 0.23165369 -0.09862424  0.01996177 -0.01565385]]

[[ 0.          0.          0.          0.        ]
 [ 0.05728609 -0.02400487  0.00509209 -0.00413775]
 [ 0.11588665 -0.04945542  0.01001569 -0.00780716]
 [ 0.17574074 -0.07620703  0.01473647 -0.01102644]
 [ 0.2367854  -0.10411314  0.01922125 -0.01381143]]

[[ 0.          0.          0.          0.        ]
 [ 0.05860055 -0.02545054  0.0049236  -0.00366941]
 [ 0.11845465 -0.05220216  0.00964439 -0.00688869]
 [ 0.17949931 -0.08010827  0.01412916 -0.00967368]
 [ 0.24166965 -0.1090209   0.01834605 -0.01203856]]

[[ 0.          0.          0.          0.        ]
 [ 0.0598541  -0.02675162  0.00472079 -0.00321928]
 [ 0.12089876 -0.05465773  0.00920556 -0.00600427]
 [ 0.1830691  -0.08357036  0.01342245 -0.00836915]
 [ 0.2462985  -0.11334075  0.01734114 -0.01032717]]

[[ 0.          0.          0.          0.        ]
 [ 0.06104466 -0.02790611  0.00448477 -0.00278499]
 [ 0.123215   -0.05681874  0.00870166 -0.00514987]
 [ 0.1864444  -0.08658913  0.01262035 -0.00710789]
 [ 0.25066466 -0.11706839  0.01621224 -0.00867202]]

[[ 0.          0.          0.          0.        ]
 [ 0.06217034 -0.02891263  0.00421689 -0.00236488]
 [ 0.12539974 -0.05868302  0.00813558 -0.0043229 ]
 [ 0.18962    -0.08916228  0.01172747 -0.00588703]
 [ 0.25476152 -0.12020195  0.0149659  -0.00707059]]

[[ 0.          0.          0.          0.        ]
 [ 0.0632294  -0.0297704   0.00391869 -0.00195802]
 [ 0.12744965 -0.06024965  0.00751058 -0.00352215]
 [ 0.19259118 -0.09128932  0.010749   -0.00470571]
 [ 0.25858315 -0.12274205  0.01360941 -0.00552288]]

[[ 0.          0.          0.          0.        ]
 [ 0.06422026 -0.03047925  0.00359189 -0.00156413]
 [ 0.12936178 -0.06151892  0.00683031 -0.0027477 ]
 [ 0.19535375 -0.09297166  0.00969072 -0.00356487]
 [ 0.26212435 -0.12469183  0.01215086 -0.00403112]]

[[ 0.          0.          0.          0.        ]
 [ 0.06514152 -0.03103967  0.00323842 -0.00118356]
 [ 0.1311335  -0.0624924   0.00609883 -0.00200074]
 [ 0.19790409 -0.09421258  0.00855897 -0.00246699]
 [ 0.26538061 -0.12605693  0.01059908 -0.00259939]]

[[ 0.          0.          0.          0.        ]
 [ 0.06599198 -0.03145273  0.0028604  -0.00081717]
 [ 0.13276257 -0.06317291  0.00532054 -0.00128343]
 [ 0.20023909 -0.09501726  0.00736066 -0.00141583]
 [ 0.26834822 -0.12684551  0.00896365 -0.00123327]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.67705915e-02 -3.17201756e-02  2.46013985e-03 -4.66252635e-04]
 [ 1.34247115e-01 -6.35645279e-02  4.50025353e-03 -5.98659479e-04]
 [ 2.02356242e-01 -9.53927785e-02  6.10324126e-03 -4.16097118e-04]
 [ 2.71024193e-01 -1.27068261e-01  7.25483286e-03  6.06682285e-05]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.74765238e-02 -3.18443523e-02  2.04011369e-03 -1.32406844e-04]
 [ 1.35585650e-01 -6.36726030e-02  3.64310142e-03  5.01555173e-05]
 [ 2.04253601e-01 -9.53480855e-02  4.79469301e-03  5.26920864e-04]
 [ 2.73406352e-01 -1.26738364e-01  5.48360820e-03  1.27525895e-03]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.81091266e-02 -3.18282506e-02  1.60298773e-03  1.82562361e-04]
 [ 1.36777078e-01 -6.35037332e-02  2.75457933e-03  6.59327708e-04]
 [ 2.05929828e-01 -9.48940113e-02  3.44349452e-03  1.40766580e-03]
 [ 2.75493312e-01 -1.25871487e-01  3.66159405e-03  2.40319777e-03]]

[[ 0.          0.          0.          0.        ]
 [ 0.06866795 -0.03167548  0.00115159  0.00047677]
 [ 0.1378207  -0.06306576  0.00184051  0.0012251 ]
 [ 0.20738419 -0.09404324  0.00205861  0.00222064]
 [ 0.2772845  -0.12448574  0.00180103  0.00343743]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.91527507e-02 -3.13902781e-02  6.88915192e-04  7.48338088e-04]
 [ 1.38716234e-01 -6.23677536e-02  9.07014720e-04  1.74387006e-03]
 [ 2.08616551e-01 -9.28102613e-02  6.49441089e-04  2.96066940e-03]
 [ 2.78780175e-01 -1.22601648e-01 -8.52521357e-05  4.37153381e-03]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.95634837e-02 -3.09774755e-02  2.18099528e-04  9.95531973e-04]
 [ 1.39463800e-01 -6.14199832e-02 -3.94741032e-05  2.21233131e-03]
 [ 2.09627424e-01 -9.12113699e-02 -7.74167328e-04  3.62319573e-03]
 [ 2.79981417e-01 -1.20242054e-01 -1.98389883e-03  5.19997305e-03]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.99003163e-02 -3.04425077e-02 -2.57573631e-04  1.21679934e-03]
 [ 1.40063940e-01 -6.02338945e-02 -9.92266856e-04  2.62766375e-03]
 [ 2.10417933e-01 -8.92645784e-02 -2.20199836e-03  4.20444108e-03]
 [ 2.80890154e-01 -1.17432086e-01 -3.88105618e-03  5.91839195e-03]]

[[ 0.          0.          0.          0.        ]
 [ 0.07016362 -0.02979139 -0.00073469  0.00141086]
 [ 0.14051762 -0.05882207 -0.00194442  0.00298764]
 [ 0.21098984 -0.08698958 -0.00362348  0.00470159]
 [ 0.28150915 -0.11419905 -0.00576244  0.00652377]]

[[ 0.          0.          0.          0.        ]
 [ 0.07035399 -0.02903068 -0.00120973  0.00157678]
 [ 0.14082621 -0.05719819 -0.00288879  0.00329073]
 [ 0.21134553 -0.08440767 -0.00502774  0.00511291]
 [ 0.28184203 -0.11057235 -0.00761337  0.00701455]]

[[ 0.          0.          0.          0.        ]
 [ 0.07047222 -0.02816751 -0.00167906  0.00171395]
 [ 0.14099154 -0.05537698 -0.00381801  0.00353613]
 [ 0.21148803 -0.08154167 -0.00640364  0.00543777]
 [ 0.28189322 -0.10658336 -0.00941888  0.00739064]]

[[ 0.          0.          0.          0.        ]
 [ 0.07051932 -0.02720948 -0.00213895  0.00182218]
 [ 0.14101581 -0.05337416 -0.00472458  0.00372382]
 [ 0.211421   -0.07841585 -0.00773982  0.00567669]
 [ 0.28166802 -0.1022653  -0.01116372  0.00765342]]

[[ 0.          0.          0.          0.        ]
 [ 0.0704965  -0.02616469 -0.00258563  0.00190164]
 [ 0.14090168 -0.05120638 -0.00560087  0.00385451]
 [ 0.21114871 -0.07505582 -0.00902477  0.00583124]
 [ 0.28117253 -0.09765309 -0.01283249  0.00780564]]

[[ 0.          0.          0.          0.        ]
 [ 0.07040519 -0.02504169 -0.00301524  0.00195287]
 [ 0.14065221 -0.04889113 -0.00643914  0.00392961]
 [ 0.21067604 -0.0714884  -0.01024686  0.005904  ]
 [ 0.28041368 -0.09278324 -0.01440967  0.00785121]]

[[ 0.          0.          0.          0.        ]
 [ 0.07024702 -0.02384944 -0.0034239   0.00197674]
 [ 0.14027085 -0.04644671 -0.00723162  0.00395114]
 [ 0.21000849 -0.06774155 -0.01139444  0.00589835]
 [ 0.27939916 -0.08769361 -0.01587974  0.00779503]]

[[ 0.          0.          0.          0.        ]
 [ 0.07002383 -0.02259727 -0.00380772  0.0019744 ]
 [ 0.13976147 -0.0438921  -0.00797053  0.00392161]
 [ 0.20915214 -0.06384417 -0.01245583  0.00581829]
 [ 0.27813747 -0.08242331 -0.01722721  0.00764265]]

[[ 0.          0.          0.          0.        ]
 [ 0.06973764 -0.02129483 -0.00416281  0.00194721]
 [ 0.13912831 -0.0412469  -0.00864811  0.00384389]
 [ 0.20811364 -0.05982604 -0.01341949  0.00566825]
 [ 0.27663785 -0.07701243 -0.01843679  0.00740002]]

[[ 0.          0.          0.          0.        ]
 [ 0.06939067 -0.01995207 -0.0044853   0.00189668]
 [ 0.13837601 -0.03853121 -0.00925668  0.00372104]
 [ 0.20690021 -0.0557176  -0.01427398  0.00545281]
 [ 0.27491025 -0.07150189 -0.01949343  0.0070731 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.06898533 -0.01857914 -0.00477138  0.00182436]
 [ 0.13750954 -0.03576553 -0.00978868  0.00355613]
 [ 0.20551958 -0.05154983 -0.01500813  0.00517642]
 [ 0.27296534 -0.06593321 -0.02038241  0.00666751]]

[[ 0.          0.          0.          0.        ]
 [ 0.06852421 -0.01718639 -0.00501731  0.00173177]
 [ 0.13653425 -0.03297069 -0.01023675  0.00335206]
 [ 0.20398    -0.04735407 -0.01561103  0.00484315]
 [ 0.27081442 -0.06034824 -0.02108949  0.00618816]]

[[ 0.          0.          0.          0.        ]
 [ 0.06801004 -0.0157843  -0.00521944  0.00162029]
 [ 0.1354558  -0.03016768 -0.01059373  0.00311138]
 [ 0.20229021 -0.04316185 -0.01607219  0.00445639]
 [ 0.26846943 -0.05478899 -0.021601    0.00563891]]

[[ 0.          0.          0.          0.        ]
 [ 0.06744576 -0.01438338 -0.00537428  0.00149109]
 [ 0.13428017 -0.02737755 -0.01085274  0.00283609]
 [ 0.20045939 -0.03900469 -0.01638155  0.00401862]
 [ 0.2659429  -0.04929731 -0.02190392  0.00502232]]

[[ 0.          0.          0.          0.        ]
 [ 0.06683441 -0.01299417 -0.00547846  0.00134501]
 [ 0.13301363 -0.02462131 -0.01100727  0.00252754]
 [ 0.19849715 -0.03491393 -0.01652964  0.00353123]
 [ 0.2632479  -0.04391468 -0.02198603  0.00433933]]

[[ 0.          0.          0.          0.        ]
 [ 0.06617922 -0.01162714 -0.00552881  0.00118253]
 [ 0.13166274 -0.02191976 -0.01105117  0.00218623]
 [ 0.19641349 -0.03092051 -0.01650757  0.00299432]
 [ 0.26039798 -0.03868194 -0.02183604  0.00358916]]

[[ 0.          0.          0.          0.        ]
 [ 0.06548351 -0.01029262 -0.00552236  0.0010037 ]
 [ 0.13023427 -0.01929338 -0.01097876  0.00181179]
 [ 0.19421876 -0.0270548  -0.01630723  0.00240663]
 [ 0.25740716 -0.03363895 -0.02144365  0.00276927]]

[[ 0.          0.          0.          0.        ]
 [ 0.06475075 -0.00900076 -0.0054564   0.00080809]
 [ 0.12873525 -0.01676218 -0.01078487  0.00140293]
 [ 0.19192364 -0.02334633 -0.01592129  0.00176557]
 [ 0.25428984 -0.0288244  -0.02079975  0.00187545]]

[[ 0.          0.          0.          0.        ]
 [ 0.06398449 -0.00776142 -0.00532847  0.00059484]
 [ 0.12717289 -0.01434557 -0.01046489  0.00095748]
 [ 0.18953909 -0.01982364 -0.01534335  0.00106735]
 [ 0.25106078 -0.02427546 -0.01989645  0.00090207]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.31883965e-02 -6.58415179e-03 -5.13642462e-03  3.62641347e-04]
 [ 1.25554591e-01 -1.20622224e-02 -1.00148784e-02  4.72513462e-04]
 [ 1.87076284e-01 -1.65140393e-02 -1.45679856e-02  3.07227746e-04]
 [ 2.47735029e-01 -2.00275095e-02 -1.87273171e-02 -1.57408211e-04]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.23661949e-02 -5.47807057e-03 -4.87845382e-03  1.09872116e-04]
 [ 1.23887887e-01 -9.92988752e-03 -9.43156096e-03 -5.54136004e-05]
 [ 1.84546632e-01 -1.34433577e-02 -1.35908925e-02 -5.20049557e-04]
 [ 2.44327880e-01 -1.61138323e-02 -1.72873933e-02 -1.30974192e-03]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.15216924e-02 -4.45181695e-03 -4.55310714e-03 -1.65285716e-04]
 [ 1.22180437e-01 -7.96528714e-03 -8.71243871e-03 -6.29921673e-04]
 [ 1.81961685e-01 -1.06357618e-02 -1.24089395e-02 -1.41961404e-03]
 [ 2.40854806e-01 -1.25653259e-02 -1.55733855e-02 -2.56093434e-03]]

[[ 0.          0.          0.          0.        ]
 [ 0.06065875 -0.00351347 -0.00415933 -0.00046464]
 [ 0.12043999 -0.00618394 -0.00785583 -0.00125433]
 [ 0.17933311 -0.00811351 -0.01102028 -0.00239565]
 [ 0.23733141 -0.0094102  -0.01358376 -0.00391493]]

[[ 0.          0.          0.          0.        ]
 [ 0.05978125 -0.00267047 -0.0036965  -0.00078969]
 [ 0.11867437 -0.00460004 -0.00686095 -0.00193101]
 [ 0.17667266 -0.00589673 -0.00942443 -0.0034503 ]
 [ 0.23377336 -0.00667365 -0.01131888 -0.005372  ]]

[[ 0.          0.          0.          0.        ]
 [ 0.05889312 -0.00192956 -0.00316445 -0.00114132]
 [ 0.11689141 -0.00322625 -0.00572793 -0.00266061]
 [ 0.17399211 -0.00400318 -0.00762238 -0.0045823 ]
 [ 0.23019634 -0.00437762 -0.00878109 -0.00692666]]

[[ 0.          0.          0.          0.        ]
 [ 0.05799829 -0.00129669 -0.00256349 -0.00151929]
 [ 0.11509899 -0.00207362 -0.00445794 -0.00344098]
 [ 0.17130322 -0.00244806 -0.00561665 -0.00578534]
 [ 0.22661601 -0.00254043 -0.00597486 -0.00856531]]

[[ 0.          0.          0.          0.        ]
 [ 0.05710069 -0.00077693 -0.00189445 -0.0019217 ]
 [ 0.11330493 -0.00115137 -0.00305316 -0.00426605]
 [ 0.16861772 -0.00124374 -0.00341138 -0.00704602]
 [ 0.22304791 -0.0011765  -0.00290693 -0.01026323]]

[[ 0.          0.          0.          0.        ]
 [ 0.05620423 -0.00037444 -0.00115871 -0.00234436]
 [ 0.11151702 -0.00046681 -0.00151693 -0.00512433]
 [ 0.16594721 -0.00039957 -0.00101247 -0.00834154]
 [ 0.21950742 -0.00029609  0.00041367 -0.01198256]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.53127879e-02 -9.23668168e-05 -3.58218398e-04 -2.77996891e-03]
 [ 1.09742978e-01 -2.51250064e-05  1.46233571e-04 -5.99717807e-03]
 [ 1.63303186e-01  7.83508626e-05  1.57237906e-03 -9.63820684e-03]
 [ 2.16009676e-01  9.49464111e-05  3.97551692e-03 -1.36749827e-02]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.44301906e-02  6.72418104e-05  5.04451968e-04 -3.21720916e-03]
 [ 1.07990398e-01  1.70717679e-04  1.93059746e-03 -6.85823793e-03]
 [ 1.60696888e-01  1.87313228e-04  4.33373532e-03 -1.08950138e-02]
 [ 2.12569433e-01 -4.71743169e-06  7.76494144e-03 -1.52894641e-02]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.35602071e-02  1.03475869e-04  1.42614549e-03 -3.64102878e-03]
 [ 1.06266698e-01  1.20071418e-04  3.82928335e-03 -7.67780460e-03]
 [ 1.58139243e-01 -7.19592421e-05  7.26048947e-03 -1.20722550e-02]
 [ 2.09200972e-01 -5.91970121e-04  1.17661703e-02 -1.67804402e-02]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.27064904e-02  1.65955485e-05  2.40313786e-03 -4.03677582e-03]
 [ 1.04579036e-01 -1.75435111e-04  5.83434398e-03 -8.43122621e-03]
 [ 1.55640765e-01 -6.95445990e-04  1.03400248e-02 -1.31394114e-02]
 [ 2.05918023e-01 -1.65946049e-03  1.59615231e-02 -1.81146162e-02]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.18725453e-02 -1.92030660e-04  3.43120612e-03 -4.39445039e-03]
 [ 1.02934275e-01 -7.12041538e-04  7.93688696e-03 -9.10263559e-03]
 [ 1.53211533e-01 -1.67605604e-03  1.35583852e-02 -1.40778403e-02]
 [ 2.02733738e-01 -3.19591052e-03  2.03316164e-02 -1.92728317e-02]]

[[ 0.          0.          0.          0.        ]
 [ 0.05106173 -0.00052001  0.00450568 -0.00470819]
 [ 0.10133899 -0.00148403  0.01012718 -0.00968339]
 [ 0.15086119 -0.00300388  0.01690041 -0.01487838]
 [ 0.1996607  -0.00518645  0.02485555 -0.02024686]]

[[ 0.          0.          0.          0.        ]
 [ 0.05027726 -0.00096401  0.0056215  -0.0049752 ]
 [ 0.09979946 -0.00248387  0.01239473 -0.0101702 ]
 [ 0.14859897 -0.00466644  0.02034987 -0.01553867]
 [ 0.19671092 -0.00761292  0.02951111 -0.02103621]]

[[ 0.          0.          0.          0.        ]
 [ 0.04952221 -0.00151985  0.00677323 -0.00519499]
 [ 0.09832171 -0.00370242  0.01472837 -0.01056347]
 [ 0.14643366 -0.00664891  0.02388961 -0.016061  ]
 [ 0.19389585 -0.01045423  0.0342749  -0.02164549]]

[[ 0.          0.          0.          0.        ]
 [ 0.04879951 -0.00218257  0.00795514 -0.00536848]
 [ 0.09691146 -0.00512905  0.01711638 -0.01086601]
 [ 0.14437365 -0.00893437  0.02750167 -0.0164505 ]
 [ 0.19122637 -0.01368659  0.0391226  -0.02208228]]

[[ 0.          0.          0.          0.        ]
 [ 0.04811195 -0.00294649  0.00916123 -0.00549753]
 [ 0.09557414 -0.0067518   0.01954653 -0.01108202]
 [ 0.14242686 -0.01150403  0.03116745 -0.0167138 ]
 [ 0.18871274 -0.01728389  0.04402909 -0.02235548]]

[[ 0.          0.          0.          0.        ]
 [ 0.04746219 -0.00380532  0.01038529 -0.00558449]
 [ 0.09431491 -0.00855754  0.02200622 -0.01121627]
 [ 0.14060078 -0.0143374   0.03486785 -0.01685794]
 [ 0.18636463 -0.02121789  0.04896866 -0.02247406]]

[[ 0.          0.          0.          0.        ]
 [ 0.04685272 -0.00475222  0.01162093 -0.00563178]
 [ 0.09313859 -0.01053209  0.02448256 -0.01127345]
 [ 0.13890244 -0.01741257  0.03858337 -0.01688957]
 [ 0.18419106 -0.02545856  0.05391517 -0.02244617]]

[[ 0.          0.          0.          0.        ]
 [ 0.04628588 -0.00577986  0.01286163 -0.00564167]
 [ 0.09204972 -0.01266035  0.02696244 -0.01125779]
 [ 0.13733834 -0.02070634  0.04229424 -0.01681439]
 [ 0.1822004  -0.02997431  0.05884225 -0.02227848]]

[[ 0.          0.          0.          0.        ]
 [ 0.04576384 -0.00688049  0.0141008  -0.00561612]
 [ 0.09105247 -0.01492648  0.02943261 -0.01117271]
 [ 0.13591453 -0.02419445  0.04598062 -0.01663681]
 [ 0.18040032 -0.03473225  0.06372343 -0.02197587]]

[[ 0.          0.          0.          0.        ]
 [ 0.04528863 -0.00804599  0.01533181 -0.0055566 ]
 [ 0.09015069 -0.01731396  0.03187982 -0.01102069]
 [ 0.13463648 -0.02785176  0.04962262 -0.01635975]
 [ 0.17879777 -0.03969841  0.06853232 -0.0215412 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.04486206 -0.00926797  0.01654801 -0.00546409]
 [ 0.08934786 -0.01980577  0.03429082 -0.01080315]
 [ 0.13350915 -0.03165242  0.05320051 -0.0159846 ]
 [ 0.17739895 -0.04483801  0.07324279 -0.02097542]]

[[ 0.          0.          0.          0.        ]
 [ 0.0444858  -0.0105378   0.01774281 -0.00533906]
 [ 0.08864709 -0.02238445  0.0366525  -0.01052051]
 [ 0.13253689 -0.03557004  0.05669478 -0.01551133]
 [ 0.17620929 -0.05011566  0.0778291  -0.02027767]]

[[ 0.          0.          0.          0.        ]
 [ 0.04416129 -0.01184665  0.0189097  -0.00518145]
 [ 0.0880511  -0.02503224  0.03895198 -0.01017227]
 [ 0.1317235  -0.03957786  0.06008629 -0.01493861]
 [ 0.17523342 -0.05549556  0.08226604 -0.01944556]]

[[ 0.          0.          0.          0.        ]
 [ 0.04388981 -0.01318559  0.02004228 -0.00499082]
 [ 0.08756221 -0.02773121  0.04117659 -0.00975715]
 [ 0.13107212 -0.04364891  0.06335635 -0.01426411]
 [ 0.17447512 -0.06094171  0.08652911 -0.01847556]]

[[ 0.          0.          0.          0.        ]
 [ 0.0436724  -0.01454562  0.02113432 -0.00476634]
 [ 0.08718232 -0.03046331  0.04331407 -0.00927329]
 [ 0.13058531 -0.04775612  0.06648683 -0.01348474]
 [ 0.17393734 -0.06641814  0.0905946  -0.01736332]]

[[ 0.          0.          0.          0.        ]
 [ 0.04350992 -0.01591769  0.02217975 -0.00450695]
 [ 0.08691291 -0.0332105   0.04535252 -0.00871841]
 [ 0.13026494 -0.05187252  0.06946029 -0.01259699]
 [ 0.17362215 -0.07188902  0.09443975 -0.01610411]]

[[ 0.          0.          0.          0.        ]
 [ 0.04340299 -0.01729281  0.02317276 -0.00421145]
 [ 0.08675502 -0.03595483  0.04728053 -0.00809003]
 [ 0.13011223 -0.05597132  0.07226    -0.01159715]
 [ 0.17353074 -0.07731889  0.09804285 -0.01469316]]

[[ 0.          0.          0.          0.        ]
 [ 0.04335203 -0.01866202  0.02410777 -0.00387858]
 [ 0.08670924 -0.03867852  0.04908723 -0.0073857 ]
 [ 0.13012775 -0.06002608  0.07487009 -0.01048171]
 [ 0.17366339 -0.08267281  0.10138336 -0.01312609]]

[[ 0.          0.          0.          0.        ]
 [ 0.04335721 -0.0200165   0.02497946 -0.00350712]
 [ 0.08677572 -0.04136406  0.05076232 -0.00660313]
 [ 0.13031136 -0.06401079  0.07727559 -0.00924751]
 [ 0.17401946 -0.0879165   0.10444199 -0.01139916]]

[[ 0.          0.          0.          0.        ]
 [ 0.04341851 -0.02134756  0.02578285 -0.00309601]
 [ 0.08695415 -0.04399429  0.05229613 -0.00574039]
 [ 0.13066225 -0.0679      0.07946252 -0.00789204]
 [ 0.17459741 -0.0930165   0.1072008  -0.00950957]]

[[ 0.          0.          0.          0.        ]
 [ 0.04353564 -0.02264673  0.02651327 -0.00264438]
 [ 0.08724374 -0.04655243  0.05367967 -0.00479603]
 [ 0.1311789  -0.07166894  0.08141795 -0.00641357]
 [ 0.17539476 -0.09794031  0.10964329 -0.00745566]]

[[ 0.          0.          0.          0.        ]
 [ 0.0437081  -0.02390571  0.0271664  -0.00215165]
 [ 0.08764326 -0.04902221  0.05490467 -0.00376919]
 [ 0.13185912 -0.07529359  0.08313002 -0.00481127]
 [ 0.17640814 -0.1026565   0.11175443 -0.00523697]]

[[ 0.          0.          0.          0.        ]
 [ 0.04393516 -0.0251165   0.02773828 -0.00161754]
 [ 0.08815102 -0.05138788  0.05596362 -0.00265962]
 [ 0.13270004 -0.07875079  0.08458804 -0.00308532]
 [ 0.17763324 -0.10713483  0.11352078 -0.00285435]]

[[ 0.          0.          0.          0.        ]
 [ 0.04421586 -0.02627137  0.02822534 -0.00104209]
 [ 0.08876488 -0.05363429  0.05684976 -0.00146778]
 [ 0.13369808 -0.08201833  0.0857825  -0.00123682]
 [ 0.17906489 -0.11134638  0.11493047 -0.00030989]]

[[ 0.          0.          0.          0.        ]
 [ 0.04454901 -0.02736291  0.02862442 -0.00042569]
 [ 0.08948222 -0.05574696  0.05755716 -0.00019473]
 [ 0.13484903 -0.08507501  0.08670513  0.0007322 ]
 [ 0.180697   -0.11526363  0.11597331  0.00239324]]

[[ 0.          0.          0.          0.        ]
 [ 0.04493321 -0.02838404  0.02893274  0.00023097]
 [ 0.09030001 -0.0577121   0.05808071  0.0011579 ]
 [ 0.13614799 -0.08790072  0.08734889  0.00281893]
 [ 0.18252265 -0.11886054  0.11664077  0.00525092]]

[[ 0.          0.          0.          0.        ]
 [ 0.04536681 -0.02932805  0.02914797  0.00092693]
 [ 0.09121478 -0.05951667  0.05841615  0.00258796]
 [ 0.13758944 -0.0904765   0.08770803  0.00501995]
 [ 0.18453406 -0.12211268  0.11692603  0.0082584 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.04584798 -0.03018862  0.02926818  0.00166103]
 [ 0.09222264 -0.06114845  0.05856006  0.00409302]
 [ 0.13916725 -0.09278463  0.08777806  0.00733147]
 [ 0.18672265 -0.12499724  0.11682398  0.01141062]]

[[ 0.          0.          0.          0.        ]
 [ 0.04637466 -0.03095983  0.02929188  0.00243199]
 [ 0.09331927 -0.062596    0.05850988  0.00567044]
 [ 0.14087467 -0.09480862  0.0875558   0.00974958]
 [ 0.18907906 -0.12749315  0.11633124  0.01470254]]

[[ 0.          0.          0.          0.        ]
 [ 0.04694461 -0.03163618  0.029218    0.00323845]
 [ 0.09450001 -0.06384879  0.05826392  0.00731759]
 [ 0.1427044  -0.09653333  0.08703936  0.01227055]
 [ 0.1915932  -0.12958112  0.11544615  0.01812958]]

[[ 0.          0.          0.          0.        ]
 [ 0.0475554  -0.03221261  0.02904592  0.00407914]
 [ 0.09575979 -0.06489715  0.05782136  0.0090321 ]
 [ 0.14464859 -0.09794494  0.08622815  0.01489113]
 [ 0.19425426 -0.13124366  0.11416877  0.02168804]]

[[ 0.          0.          0.          0.        ]
 [ 0.04820439 -0.03268453  0.02877544  0.00495296]
 [ 0.09709319 -0.06573233  0.05718223  0.01081199]
 [ 0.14669886 -0.09903105  0.08512285  0.01760889]
 [ 0.19705076 -0.13246518  0.11250084  0.02537542]]

[[ 0.          0.          0.          0.        ]
 [ 0.0488888  -0.03304779  0.02840679  0.00585903]
 [ 0.09849447 -0.06634652  0.05634741  0.01265594]
 [ 0.14884637 -0.09978065  0.0837254   0.02042247]
 [ 0.1999706  -0.13323198  0.11044579  0.02919089]]

[[ 0.          0.          0.          0.        ]
 [ 0.04960567 -0.03329872  0.02794062  0.0067969 ]
 [ 0.09995757 -0.06673286  0.05531861  0.01456343]
 [ 0.1510818  -0.10018418  0.082039    0.02333186]
 [ 0.20300111 -0.13353227  0.1080087   0.0331355 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.0503519  -0.03343413  0.02737799  0.00776653]
 [ 0.10147613 -0.06688546  0.05409839  0.01653496]
 [ 0.15339544 -0.10023355  0.08006809  0.0263386 ]
 [ 0.20612907 -0.13335623  0.10519626  0.03721242]]

[[ 0.          0.          0.          0.        ]
 [ 0.05112424 -0.03345133  0.02672039  0.00876842]
 [ 0.10304354 -0.06679941  0.05269009  0.01857206]
 [ 0.15577717 -0.0999221   0.07781827  0.02944589]
 [ 0.20934076 -0.132696    0.10201675  0.04142702]]

[[ 0.          0.          0.          0.        ]
 [ 0.05191931 -0.03334808  0.0259697   0.00980364]
 [ 0.10465294 -0.06647077  0.05109788  0.02067746]
 [ 0.15821652 -0.09924468  0.07529635  0.03265859]
 [ 0.21262202 -0.13154568  0.09847997  0.04578677]]

[[ 0.          0.          0.          0.        ]
 [ 0.05273363 -0.03312269  0.02512818  0.01087382]
 [ 0.10629722 -0.06589659  0.04932665  0.02285495]
 [ 0.16070271 -0.0981976   0.07251027  0.03598313]
 [ 0.21595828 -0.12990133  0.09459726  0.05030097]]

[[ 0.          0.          0.          0.        ]
 [ 0.05356359 -0.03277391  0.02419848  0.01198113]
 [ 0.10796908 -0.06507491  0.0473821   0.02510931]
 [ 0.16322465 -0.09677864  0.06946908  0.03942715]
 [ 0.21933459 -0.12776097  0.09038137  0.05498018]]

[[ 0.          0.          0.          0.        ]
 [ 0.0544055  -0.032301    0.02318362  0.01312818]
 [ 0.10966106 -0.06400474  0.0452706   0.02744601]
 [ 0.165771   -0.09498706  0.06618289  0.04299905]
 [ 0.22273568 -0.12512455  0.0858465   0.05983544]]

[[ 0.          0.          0.          0.        ]
 [ 0.05525557 -0.03170373  0.02208698  0.01431784]
 [ 0.1113655  -0.06268606  0.04299927  0.02987087]
 [ 0.16833018 -0.09282355  0.06266288  0.04670726]
 [ 0.22614596 -0.12199397  0.08100821  0.06487709]]

[[ 0.          0.          0.          0.        ]
 [ 0.05610994 -0.03098232  0.02091229  0.01555303]
 [ 0.11307461 -0.06111982  0.0405759   0.03238943]
 [ 0.1708904  -0.09029023  0.05892123  0.05055925]
 [ 0.22954961 -0.11837299  0.07588337  0.07011323]]

[[ 0.          0.          0.          0.        ]
 [ 0.05696468 -0.03013749  0.01966361  0.01683639]
 [ 0.11478046 -0.05930791  0.03800894  0.03500622]
 [ 0.17343967 -0.08739066  0.05497108  0.05456019]
 [ 0.23293051 -0.11426725  0.07049016  0.07554771]]

[[ 0.          0.          0.          0.        ]
 [ 0.05781578 -0.02917042  0.01834533  0.01816983]
 [ 0.11647499 -0.05725317  0.03530747  0.0377238 ]
 [ 0.17596583 -0.08412976  0.05082655  0.05871132]
 [ 0.23627234 -0.10968423  0.06484797  0.0811777 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.05865921 -0.02808275  0.01696215  0.01955397]
 [ 0.11815005 -0.05495934  0.03248122  0.04054149]
 [ 0.17845655 -0.08051381  0.04650265  0.06300787]
 [ 0.23955854 -0.10463316  0.05897744  0.08699062]]

[[ 0.          0.          0.          0.        ]
 [ 0.05949084 -0.02687659  0.01551908  0.02098752]
 [ 0.11979734 -0.05243106  0.0295405   0.0434539 ]
 [ 0.18089933 -0.07655041  0.04201529  0.06743665]
 [ 0.24277234 -0.09912505  0.05290035  0.09296119]]

[[ 0.          0.          0.          0.        ]
 [ 0.0603065  -0.02555447  0.01402143  0.02246638]
 [ 0.12140849 -0.04967382  0.02649622  0.04644913]
 [ 0.18328151 -0.07224846  0.03738128  0.07197367]
 [ 0.24589675 -0.09317263  0.04663968  0.09905112]]

[[ 0.          0.          0.          0.        ]
 [ 0.06110199 -0.02411935  0.01247479  0.02398275]
 [ 0.122975   -0.04669399  0.02335985  0.04950729]
 [ 0.18559024 -0.06761816  0.03261825  0.07658474]
 [ 0.24891456 -0.08679045  0.04021951  0.10521308]]

[[ 0.          0.          0.          0.        ]
 [ 0.06187301 -0.02257464  0.01088506  0.02552454]
 [ 0.12448825 -0.04349881  0.02014346  0.05260199]
 [ 0.18781257 -0.06267109  0.02774472  0.08123033]
 [ 0.25180848 -0.07999485  0.03366496  0.11139614]]

[[ 0.          0.          0.          0.        ]
 [ 0.06261524 -0.02092417  0.0092584   0.02707745]
 [ 0.12593956 -0.04009646  0.01685966  0.05570579]
 [ 0.18993547 -0.05742021  0.02277991  0.0858716 ]
 [ 0.25456123 -0.07280396  0.02700204  0.11755171]]

[[ 0.          0.          0.          0.        ]
 [ 0.06332432 -0.01917229  0.00760126  0.02862834]
 [ 0.12732023 -0.03649604  0.0135215   0.05879415]
 [ 0.19194599 -0.05187979  0.01774364  0.09047426]
 [ 0.25715568 -0.06523755  0.02025739  0.12363728]]

[[ 0.          0.          0.          0.        ]
 [ 0.06399592 -0.01732376  0.00592025  0.03016581]
 [ 0.12862168 -0.0327075   0.01014238  0.06184592]
 [ 0.19383136 -0.04606526  0.01265613  0.09500895]
 [ 0.25957499 -0.05731684  0.01345806  0.12961669]]

[[ 0.          0.          0.          0.        ]
 [ 0.06462576 -0.01538375  0.00422214  0.03168011]
 [ 0.12983544 -0.0287415   0.00673589  0.06484314]
 [ 0.19557907 -0.03999308  0.00753782  0.09945088]
 [ 0.26180279 -0.04906436  0.0066313   0.13545966]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.52096803e-02 -1.33577555e-02  2.51375005e-03  3.31630240e-02]
 [ 1.30953309e-01 -2.46093364e-02  3.31567954e-03  6.77707682e-02]
 [ 1.97177027e-01 -3.36806121e-02  2.40916388e-03  1.03779549e-01]
 [ 2.63823274e-01 -4.05037236e-02 -1.95689280e-04  1.41141379e-01]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.57436283e-02 -1.12515808e-02  8.01929485e-04  3.46077442e-02]
 [ 1.31967347e-01 -2.03228566e-02 -1.04586166e-04  7.06165250e-02]
 [ 1.98613594e-01 -2.71459680e-02 -2.70943933e-03  1.07978355e-01]
 [ 2.65621312e-01 -3.16595123e-02 -6.99590635e-03  1.46642011e-01]]

[[ 0.          0.          0.          0.        ]
 [ 0.06622372 -0.00907128 -0.00090652  0.03600878]
 [ 0.13286997 -0.01589439 -0.00351137  0.07337061]
 [ 0.19987768 -0.02040793 -0.00779784  0.11203427]
 [ 0.26718254 -0.02255712 -0.01374273  0.15194625]]

[[ 0.          0.          0.          0.        ]
 [ 0.06664625 -0.00682311 -0.00260485  0.03736183]
 [ 0.13365396 -0.01133666 -0.00689132  0.07602549]
 [ 0.20095882 -0.01348584 -0.01283621  0.11593746]
 [ 0.26849345 -0.01322261 -0.02041006  0.15704281]]

[[ 0.          0.          0.          0.        ]
 [ 0.06700772 -0.00451354 -0.00428647  0.03866366]
 [ 0.13431257 -0.00666273 -0.01023136  0.07857564]
 [ 0.20184721 -0.00639949 -0.01780521  0.11968098]
 [ 0.26954148 -0.00368262 -0.02697247  0.16192401]]

[[ 0.          0.          0.          0.        ]
 [ 0.06730486 -0.00214918 -0.00594489  0.03991198]
 [ 0.13483949 -0.00188595 -0.01351874  0.08101732]
 [ 0.20253376  0.00083092 -0.022686    0.12326035]
 [ 0.27031503  0.00603575 -0.0334053   0.16658524]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.75346324e-02  2.63233717e-04 -7.57384779e-03  4.11053453e-02]
 [ 1.35228906e-01  2.98010795e-03 -1.67411097e-02  8.33483704e-02]
 [ 2.03010179e-01  8.18493537e-03 -2.74604094e-02  1.26673263e-01]
 [ 2.70803586e-01  1.59050656e-02 -3.96847941e-02  1.71024582e-01]]

[[ 0.          0.          0.          0.        ]
 [ 0.06769427  0.00271687 -0.00916726  0.04224303]
 [ 0.13547555  0.0079217  -0.01988656  0.08556792]
 [ 0.20326895  0.01564183 -0.03211095  0.12991924]
 [ 0.27099769  0.02589762 -0.04578816  0.17524231]]

[[ 0.          0.          0.          0.        ]
 [ 0.06778127  0.00520483 -0.0107193   0.04332489]
 [ 0.13557468  0.01292496 -0.02294368  0.08767621]
 [ 0.20330342  0.02318075 -0.0366209   0.13299929]
 [ 0.27088903  0.03598554 -0.0516937   0.17924051]]

[[ 0.          0.          0.          0.        ]
 [ 0.06779341  0.00772013 -0.01222438  0.04435132]
 [ 0.13552214  0.01797592 -0.0259016   0.08967439]
 [ 0.20310776  0.03078071 -0.0409744   0.13591562]
 [ 0.27047046  0.04614085 -0.05738082  0.18302267]]

[[ 0.          0.          0.          0.        ]
 [ 0.06772874  0.01025579 -0.01367722  0.04532307]
 [ 0.13531435  0.02306058 -0.02875001  0.0915643 ]
 [ 0.20267706  0.03842072 -0.04515643  0.13867135]
 [ 0.26973602  0.05633557 -0.06283017  0.18659329]]

[[ 0.          0.          0.          0.        ]
 [ 0.06758562  0.01280479 -0.01507279  0.04624123]
 [ 0.13494832  0.02816493 -0.03147922  0.09334827]
 [ 0.20200728  0.04607978 -0.04915295  0.14127021]
 [ 0.26868093  0.06654178 -0.06802363  0.18995756]]

[[ 0.          0.          0.          0.        ]
 [ 0.06736271  0.01536014 -0.01640642  0.04710705]
 [ 0.13442167  0.03327499 -0.03408015  0.09502899]
 [ 0.20109532  0.05373699 -0.05295084  0.14371633]
 [ 0.26730166  0.07673166 -0.07294444  0.19312103]]

[[ 0.          0.          0.          0.        ]
 [ 0.06705896  0.01791485 -0.01767373  0.04792194]
 [ 0.13373261  0.03837685 -0.03654442  0.09660928]
 [ 0.19993896  0.06137152 -0.05653802  0.14601398]
 [ 0.26559589  0.08687761 -0.07757715  0.19608933]]

[[ 0.          0.          0.          0.        ]
 [ 0.06667365  0.02046199 -0.01887069  0.04868735]
 [ 0.13288     0.04345667 -0.03886428  0.09809204]
 [ 0.19853692  0.06896276 -0.05990342  0.14816739]
 [ 0.26356251  0.09695227 -0.08190773  0.19886793]]

[[ 0.          0.          0.          0.        ]
 [ 0.06620635  0.02299468 -0.0199936   0.0494047 ]
 [ 0.13186327  0.04850077 -0.04103273  0.09948004]
 [ 0.19688886  0.07649028 -0.06303704  0.15018058]
 [ 0.26120167  0.1069286  -0.08592357  0.20146192]]

[[ 0.          0.          0.          0.        ]
 [ 0.06565693  0.02550609 -0.02103913  0.05007535]
 [ 0.13068251  0.0534956  -0.04304344  0.10077588]
 [ 0.19499532  0.08393392 -0.06592998  0.15205722]
 [ 0.25851472  0.11677993 -0.08961353  0.20387586]]

[[ 0.          0.          0.          0.        ]
 [ 0.06502558  0.02798951 -0.02200431  0.05070054]
 [ 0.12933839  0.05842783 -0.04489084  0.10198188]
 [ 0.19285779  0.09127384 -0.0685744   0.15380051]
 [ 0.25550424  0.12648003 -0.09296791  0.20611356]]

[[ 0.          0.          0.          0.        ]
 [ 0.06431281  0.03043832 -0.02288653  0.05128134]
 [ 0.12783221  0.06328432 -0.04657008  0.10309997]
 [ 0.19047866  0.09849052 -0.0709636   0.15541303]
 [ 0.25217402  0.13600318 -0.09597854  0.20817802]]

[[ 0.          0.          0.          0.        ]
 [ 0.0635194   0.032846   -0.02368355  0.05181863]
 [ 0.12616585  0.0680522  -0.04807707  0.10413169]
 [ 0.18786121  0.10556486 -0.073092    0.15689667]
 [ 0.24852902  0.1453242  -0.09863872  0.21007124]]

[[ 0.          0.          0.          0.        ]
 [ 0.06264645  0.03520619 -0.02439351  0.05231305]
 [ 0.12434181  0.07271886 -0.04940845  0.10507804]
 [ 0.18500962  0.1124782  -0.07495517  0.15825261]
 [ 0.24457539  0.15441854 -0.1009433   0.21179426]]

[[ 0.          0.          0.          0.        ]
 [ 0.06169536  0.03751266 -0.02501494  0.05276499]
 [ 0.12236317  0.077272   -0.05056165  0.10593955]
 [ 0.18192894  0.11921234 -0.07654979  0.15948121]
 [ 0.24032043  0.1632623  -0.10288863  0.21334709]]

[[ 0.          0.          0.          0.        ]
 [ 0.06066781  0.03975934 -0.02554672  0.05317457]
 [ 0.12023358  0.08169968 -0.05153485  0.10671622]
 [ 0.17862507  0.12574964 -0.07787369  0.16058211]
 [ 0.23577258  0.17183234 -0.1044726   0.21472875]]

[[ 0.          0.          0.          0.        ]
 [ 0.05956577  0.04194034 -0.02598813  0.05354166]
 [ 0.11795726  0.0859903  -0.05232698  0.10740754]
 [ 0.17510477  0.132073   -0.07892588  0.16155418]
 [ 0.23094138  0.1801063  -0.1056946   0.21593729]]

[[ 0.          0.          0.          0.        ]
 [ 0.05839149  0.04404996 -0.02633885  0.05386588]
 [ 0.115539    0.09013266 -0.05293775  0.10801252]
 [ 0.17137561  0.13816597 -0.07970646  0.16239563]
 [ 0.22583745  0.18806269 -0.10655556  0.21696995]]

[[ 0.          0.          0.          0.        ]
 [ 0.05714751  0.0460827  -0.0265989   0.05414664]
 [ 0.11298412  0.09411601 -0.05336762  0.10852975]
 [ 0.16744596  0.14401273 -0.08021671  0.16310406]
 [ 0.22047248  0.19568089 -0.10705792  0.2178232 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.05583661  0.0480333  -0.02676872  0.05438311]
 [ 0.11029845  0.09793002 -0.05361781  0.10895742]
 [ 0.16332497  0.14959819 -0.08045902  0.16367656]
 [ 0.21485915  0.2029413  -0.10720561  0.21849294]]

[[ 0.          0.          0.          0.        ]
 [ 0.05446184  0.04989672 -0.02684909  0.05457432]
 [ 0.10748836  0.10156488 -0.0536903   0.10929345]
 [ 0.15902255  0.15490799 -0.0804369   0.16410983]
 [ 0.20901116  0.20982532 -0.10700407  0.2189746 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.05302652  0.05166816 -0.02684121  0.05471914]
 [ 0.1045607   0.10501127 -0.0535878   0.10953551]
 [ 0.15454932  0.1599286  -0.08015497  0.16440029]
 [ 0.20294313  0.21631544 -0.10646017  0.21926338]]

[[ 0.          0.          0.          0.        ]
 [ 0.05153418  0.05334311 -0.0267466   0.05481637]
 [ 0.1015228   0.10826043 -0.05331377  0.10968115]
 [ 0.14991661  0.16464728 -0.07961897  0.16454425]
 [ 0.19667059  0.22239533 -0.10558227  0.21935441]]

[[ 0.          0.          0.          0.        ]
 [ 0.04998861  0.05491732 -0.02656717  0.05486477]
 [ 0.09838242  0.11130417 -0.05287237  0.10972787]
 [ 0.14513641  0.16905222 -0.07883568  0.16453803]
 [ 0.19020996  0.22804983 -0.10438012  0.21924293]]

[[ 0.          0.          0.          0.        ]
 [ 0.04839381  0.05638685 -0.0263052   0.0548631 ]
 [ 0.0951478   0.1141349  -0.0522685   0.10967326]
 [ 0.14022135  0.1731325  -0.07781294  0.16437816]
 [ 0.18357846  0.23326504 -0.10286485  0.21892458]]

[[ 0.          0.          0.          0.        ]
 [ 0.04675399  0.05774805 -0.0259633   0.05481016]
 [ 0.09182754  0.11674565 -0.05150774  0.10951506]
 [ 0.13518466  0.1768782  -0.07655965  0.16406148]
 [ 0.17679409  0.23802842 -0.10104898  0.21839551]]

[[ 0.          0.          0.          0.        ]
 [ 0.04507355  0.05899761 -0.02554444  0.0547049 ]
 [ 0.08843067  0.11913015 -0.05059635  0.10925132]
 [ 0.13004011  0.18028037 -0.07508568  0.16358535]
 [ 0.16987557  0.24232874 -0.0989463   0.21765268]]

[[ 0.          0.          0.          0.        ]
 [ 0.04335711  0.06013254 -0.02505191  0.05454642]
 [ 0.08496655  0.12128276 -0.04954124  0.10888045]
 [ 0.12480201  0.18333114 -0.07340186  0.16294778]
 [ 0.16284226  0.24615624 -0.09657188  0.21669401]]

[[ 0.          0.          0.          0.        ]
 [ 0.04160944  0.06115022 -0.02448933  0.05433403]
 [ 0.0814449   0.1231986  -0.04834995  0.10840136]
 [ 0.11948514  0.1860237  -0.07151998  0.1621476 ]
 [ 0.15571414  0.2495026  -0.09394201  0.21551859]]

[[ 0.          0.          0.          0.        ]
 [ 0.03983546  0.06204838 -0.02386062  0.05406733]
 [ 0.0778757   0.12487348 -0.04703065  0.10781357]
 [ 0.11410471  0.18835238 -0.06945268  0.16118456]
 [ 0.14851174  0.252361   -0.09107409  0.21412685]]

[[ 0.          0.          0.          0.        ]
 [ 0.03804025  0.06282511 -0.02317002  0.05374623]
 [ 0.07426925  0.126304   -0.04559206  0.10711723]
 [ 0.10867628  0.19031263 -0.06721346  0.16005951]
 [ 0.14125603  0.2547262  -0.08798663  0.21252069]]

[[ 0.          0.          0.          0.        ]
 [ 0.036229    0.0634789  -0.02242203  0.053371  ]
 [ 0.07063604  0.12748752 -0.04404344  0.10631328]
 [ 0.10321578  0.19190109 -0.0648166   0.15877446]
 [ 0.13396836  0.2565945  -0.08469912  0.21070367]]

[[ 0.          0.          0.          0.        ]
 [ 0.03440704  0.06400863 -0.02162141  0.05294228]
 [ 0.06698678  0.12842219 -0.04239457  0.10540347]
 [ 0.09773936  0.1931156  -0.06227709  0.15733268]
 [ 0.12667042  0.25796385 -0.08123199  0.20868102]]

[[ 0.          0.          0.          0.        ]
 [ 0.03257974  0.06441357 -0.02077316  0.05246118]
 [ 0.06333232  0.12910698 -0.04065568  0.10439039]
 [ 0.09226338  0.19395522 -0.05961058  0.15573873]
 [ 0.11938409  0.2588338  -0.07760644  0.20645974]]

[[ 0.          0.          0.          0.        ]
 [ 0.03075258  0.06469341 -0.01988252  0.05192921]
 [ 0.05968364  0.12954165 -0.03883741  0.10327755]
 [ 0.08680435  0.19442023 -0.05683327  0.15399856]
 [ 0.11213138  0.25920555 -0.07384442  0.20404861]]

[[ 0.          0.          0.          0.        ]
 [ 0.02893106  0.06484824 -0.01895489  0.05134834]
 [ 0.05605177  0.12972682 -0.03695075  0.10206935]
 [ 0.0813788   0.19451214 -0.0539619   0.1521194 ]
 [ 0.10493431  0.25908197 -0.06996844  0.20145812]]

[[ 0.          0.          0.          0.        ]
 [ 0.02712071  0.06487857 -0.01799586  0.05072101]
 [ 0.05244774  0.1296639  -0.035007    0.10077105]
 [ 0.07600325  0.19423373 -0.05101355  0.15010977]
 [ 0.09781482  0.25846756 -0.0660015   0.19870042]]

[[ 0.          0.          0.          0.        ]
 [ 0.02532703  0.06478533 -0.01701114  0.05005005]
 [ 0.04888255  0.12935516 -0.03301769  0.09938877]
 [ 0.07069412  0.19358899 -0.04800564  0.14797942]
 [ 0.09079462  0.25736845 -0.06196694  0.19578923]]

[[ 0.          0.          0.          0.        ]
 [ 0.02355552  0.06456983 -0.01600655  0.04933872]
 [ 0.04536709  0.12880366 -0.0309945   0.09792937]
 [ 0.06546759  0.19258313 -0.0449558   0.14573918]
 [ 0.08389507  0.25579239 -0.0578882   0.19273947]]

[[ 0.          0.          0.          0.        ]
 [ 0.02181157  0.06423383 -0.01498795  0.04859065]
 [ 0.04191208  0.1280133  -0.02894925  0.09640046]
 [ 0.06033956  0.19122256 -0.04188165  0.14340075]
 [ 0.07713706  0.25374869 -0.05378869  0.18956674]]

[[ 0.          0.          0.          0.        ]
 [ 0.0201005   0.06377946 -0.0139613   0.04780981]
 [ 0.03852799  0.12698873 -0.0268937   0.0948101 ]
 [ 0.05532549  0.18951485 -0.03880073  0.14097609]
 [ 0.07054081  0.25124818 -0.04969158  0.18628741]]

[[ 0.          0.          0.          0.        ]
 [ 0.01842748  0.06320926 -0.0129324   0.04700029]
 [ 0.03522498  0.12573539 -0.02483944  0.09316628]
 [ 0.05044031  0.18746871 -0.03573029  0.1384776 ]
 [ 0.06412576  0.24830315 -0.04561962  0.18291787]]

[[ 0.          0.          0.          0.        ]
 [ 0.0167975   0.06252613 -0.01190703  0.04616599]
 [ 0.03201283  0.12425945 -0.02279788  0.09147731]
 [ 0.04569828  0.18509388 -0.03268722  0.13591758]
 [ 0.05791033  0.24492725 -0.04159494  0.1794741 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.01521532  0.06173332 -0.01089085  0.04531132]
 [ 0.02890077  0.12256776 -0.02078019  0.08975159]
 [ 0.04111283  0.18240113 -0.0296879   0.13330811]
 [ 0.05191177  0.24113543 -0.03763879  0.17597126]]

[[ 0.          0.          0.          0.        ]
 [ 0.01368545  0.06083444 -0.00988934  0.04444027]
 [ 0.0258975   0.12066781 -0.01879705  0.08799679]
 [ 0.03669645  0.17940211 -0.02674794  0.13065994]
 [ 0.04614594  0.23694374 -0.03377129  0.17242247]]

[[ 0.          0.          0.          0.        ]
 [ 0.01221205  0.05983337 -0.00890771  0.04355652]
 [ 0.023011    0.11856767 -0.0168586   0.08621967]
 [ 0.03246049  0.1761093  -0.02388195  0.1279822 ]
 [ 0.04062706  0.23236925 -0.0300111   0.16883763]]

[[ 0.          0.          0.          0.        ]
 [ 0.01079894  0.0587343  -0.00795088  0.04266315]
 [ 0.02024843  0.11627593 -0.01497423  0.08442568]
 [ 0.028415    0.17253588 -0.02110338  0.12528111]
 [ 0.03536759  0.22742977 -0.02637515  0.16522237]]

[[ 0.          0.          0.          0.        ]
 [ 0.00944949  0.05754163 -0.00702335  0.04176253]
 [ 0.01761606  0.11380158 -0.0131525   0.08261796]
 [ 0.02456864  0.16869547 -0.01842426  0.12255921]
 [ 0.0303781   0.22214358 -0.02287849  0.16158738]]

[[ 0.          0.          0.          0.        ]
 [ 0.00816657  0.05625995 -0.00612915  0.04085543]
 [ 0.01511915  0.11115384 -0.01140091  0.08079668]
 [ 0.02092862  0.16460195 -0.01585514  0.11982485]
 [ 0.02566732  0.21652929 -0.01953435  0.15794793]]

[[ 0.          0.          0.          0.        ]
 [ 0.00695258  0.05489389 -0.00527176  0.03994126]
 [ 0.01276205  0.108342   -0.00972599  0.07896942]
 [ 0.01750075  0.16026935 -0.0134052   0.1170925 ]
 [ 0.02124215  0.21060586 -0.0163542   0.1543242 ]]

[[ 0.          0.          0.          0.        ]
 [ 0.00580946  0.05344811 -0.00445423  0.03902817]
 [ 0.01054817  0.10537545 -0.00813344  0.07715125]
 [ 0.01428956  0.15571196 -0.01108243  0.11438294]
 [ 0.01710777  0.2043927  -0.01334791  0.15074001]]

[[ 0.          0.          0.          0.        ]
 [ 0.00473871  0.05192734 -0.00367921  0.03812308]
 [ 0.0084801   0.10226386 -0.00662821  0.07535478]
 [ 0.0112983   0.15094459 -0.00889368  0.11171184]
 [ 0.01326773  0.19790999 -0.01052394  0.14721088]]

[[ 0.          0.          0.          0.        ]
 [ 0.00374139  0.05033651 -0.00294899  0.0372317 ]
 [ 0.0065596   0.09901725 -0.00521447  0.07358876]
 [ 0.00852903  0.14598265 -0.00684472  0.10908781]
 [ 0.00972402  0.19117881 -0.00788931  0.14374233]]

[[ 0.          0.          0.          0.        ]
 [ 0.0028182   0.04868074 -0.00226548  0.03635706]
 [ 0.00478763  0.09564614 -0.00389573  0.07185611]
 [ 0.00598262  0.1408423  -0.00494031  0.10651063]
 [ 0.00647705  0.18422128 -0.00544968  0.14032825]]

[[ 0.          0.          0.          0.        ]
 [ 0.00196943  0.0469654  -0.00163025  0.03549904]
 [ 0.00316442  0.09216156 -0.00267484  0.07015357]
 [ 0.00365884  0.13554054 -0.0031842   0.10397119]
 [ 0.00352576  0.17706065 -0.00320938  0.13695164]]

[[ 0.          0.          0.          0.        ]
 [ 0.00119499  0.04519616 -0.00104458  0.03465452]
 [ 0.00168941  0.08857514 -0.00155395  0.06847214]
 [ 0.00155633  0.13009525 -0.00157913  0.10145259]
 [ 0.00086763  0.16972134 -0.00117138  0.13358658]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.94424075e-04  4.33789790e-02 -5.09367047e-04  3.38176209e-02]
 [ 3.61344022e-04  8.48990827e-02 -5.34546245e-04  6.67980727e-02]
 [-3.27358027e-04  1.24525173e-01 -1.26801636e-04  9.89320570e-02]
 [-1.50133246e-03  1.62228950e-01  6.62704739e-04  1.30201028e-01]]

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.33080053e-04  4.15201037e-02 -2.51791987e-05  3.29804518e-02]
 [-8.21782102e-04  8.11461942e-02  3.82565410e-04  6.51144361e-02]
 [-1.99575654e-03  1.18849971e-01  1.17207179e-03  9.63834074e-02]
 [-3.58653492e-03  1.54610233e-01  2.29262215e-03  1.26760259e-01]]

[[ 0.          0.          0.          0.        ]
 [-0.0006887   0.03962609  0.00040774  0.03213398]
 [-0.00186268  0.07732987  0.00119725  0.06340296]
 [-0.00345345  0.11309013  0.0023178   0.09377981]
 [-0.00539479  0.14689301  0.00371947  0.12323037]]

[[ 0.          0.          0.          0.        ]
 [-0.00117397  0.03770378  0.00078951  0.03126897]
 [-0.00276475  0.07346404  0.00191006  0.06164582]
 [-0.00470609  0.10726692  0.00331172  0.09109638]
 [-0.00693429  0.13910609  0.00494571  0.11958156]]

[[ 0.          0.          0.          0.        ]
 [-0.00159078  0.03576026  0.00112055  0.03037685]
 [-0.00353211  0.06956314  0.00252222  0.05982741]
 [-0.00576032  0.10140232  0.00415621  0.08831259]
 [-0.00821457  0.13127913  0.00597521  0.11579099]]

[[ 0.          0.          0.          0.        ]
 [-0.00194134  0.03380288  0.00140167  0.02945056]
 [-0.00416954  0.06564205  0.00303566  0.05793574]
 [-0.00662379  0.09551887  0.00485466  0.08541413]
 [-0.00924645  0.12344247  0.00681319  0.11184487]]

In [ ]:
# Load variables
# vit = fe.DINOv2()
Tro,Xro,Uro,Iro = fu.extract_rollout_data(cohort,courses[0])

In [ ]:
Nro = Tro.shape[0]
for i in range(Nro):
    fo = th.x_to_fo(Xro[:,i])
print(fo)

In [ ]:
gv.images_to_mp4(Iro,"output.mp4",fps=20)

In [ ]:
# img1 = 1*Iro[118]
img1 = 1*Iro[270]

# img1 = Image.open("elephant1.jpeg").convert('RGB')  # or 'L' for grayscale
# img1 = np.array(img1)  # shape: (H, W, 3)
# img1 = Image.open("doorway.jpg").convert('RGB')  # or 'L' for grayscale
# img1 = np.array(img1)  # shape: (H, W, 3)
# img1 = Image.open("monitor.jpg").convert('RGB')  # or 'L' for grayscale
# img1 = np.array(img1)  # shape: (H, W, 3)

img2 = 1*Iro[270]
# img2 = Image.open("elephant2.jpeg").convert('RGB')  # or 'L' for grayscale
# img2 = np.array(img2)  # shape: (H, W, 3)

print(img1.shape)

patch_size= 16
H1, W1 = img1.shape[0], img1.shape[1]
H2, W2 = img2.shape[0], img2.shape[1]
patch_h1 = H1 // patch_size
patch_w1 = W1 // patch_size
patch_h2 = H2 // patch_size
patch_w2 = W2 // patch_size

fig, axs = plt.subplots(1, 2, figsize=(8, 3))
axs[0].imshow(img1)
axs[1].imshow(img2)

for y in range(0, H1, patch_h1):
    axs[0].axhline(y, color='red', linewidth=0.5)
for x in range(0, W1, patch_w1):
    axs[0].axvline(x, color='red', linewidth=0.5)

for y in range(0, H2, patch_h2):
    axs[1].axhline(y, color='red', linewidth=0.5)
for x in range(0, W2, patch_w2):
    axs[1].axvline(x, color='red', linewidth=0.5)

plt.tight_layout()

In [ ]:
with torch.no_grad():
    img_in1 = fu.process_image(img1).unsqueeze(0)
    img_in2 = fu.process_image(img2).unsqueeze(0)

    ptk1 = vit(img_in1).squeeze(0).view(16,16,-1)
    ptk2 = vit(img_in2).squeeze(0).view(16,16,-1)

In [ ]:
idxs = np.array([
    [ 8,  8],
    [ 8, 10],
    [11,  8],
    [11, 10],])
# idxs = np.array([
#     [ 1,  8],
#     [ 0, 10],
#     [13,  8],
#     [14, 10],])
# idxs = np.array([
#     [ 3,  2],
#     [10,  2],
#     [11, 13],
#     [ 1, 12],])
Np = idxs.shape[0]

patches = []
for i in range(Np):
    patches.append(ptk1[idxs[i,0],idxs[i,1],:])

cos_sims = torch.zeros((Np,16,16))
for i in range(Np):
    for j in range(16):
        for k in range(16):
            patch2 = ptk2[j,k,:]
            cos_sims[i,j,k] = F.cosine_similarity(patches[i],patch2,dim=0)

imgs1_hots = np.zeros((16,16))
imgs2_hots = np.zeros((16,16))
for i in range(Np):
    # max_idx = torch.argmax(cos_sims[i,:,:])
    # row,col = divmod(max_idx.item(), 16)

    imgs1_hots[idxs[i,0],idxs[i,1]] = 1
    # imgs2_hots[row,col] = 1
    imgs2_hots = (cos_sims[i,:,:] > 0.6).float()

overlay1 = fu.overlay_heatmap_on_image(imgs1_hots,img1)
overlay2 = fu.overlay_heatmap_on_image(imgs2_hots,img2)
fig, axs = plt.subplots(1, 2, figsize=(8, 3))
axs[0].imshow(overlay1)
axs[1].imshow(overlay2)

In [ ]:
Nro = Iro.shape[0]
height = Iro.shape[1]
width = Iro.shape[2]

Iout = np.zeros((Nro,height,width,3),dtype=np.uint8)
for p in range(Nro):
    img2 = 1*Iro[p]

    img_in2 = fu.process_image(img2).unsqueeze(0)        
    with torch.no_grad():
        ptk2 = vit(img_in2).squeeze(0).view(16,16,-1)

    cos_sims = torch.zeros((Np,16,16))
    for i in range(Np):
        for j in range(16):
            for k in range(16):
                patch2 = ptk2[j,k,:]
                cos_sims[i,j,k] = F.cosine_similarity(patches[i],patch2,dim=0)

    imgs2_hots = np.zeros((16,16))
    for i in range(Np):
        # max_idx = torch.argmax(cos_sims[i,:,:])
        # row,col = divmod(max_idx.item(), 16)

        # imgs2_hots[row,col] = 1
        imgs2_hots = (cos_sims[i,:,:] > 0.6).float()

        
    Iout[p,:,:,:] = fu.overlay_heatmap_on_image(imgs2_hots,img2)

gv.images_to_mp4(Iout,"output4.mp4",fps=20)